config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  
  
  get 'profile/:id', to: 'users#show', as: 'profile'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'events/:id/invite', to: 'events#invite', as: 'invite_event'
  get 'events/:id/attend', to: 'events#attend', as: 'attend_event'
  get 'users/invitations', to: 'users#invited_events', as: 'invited_events'
  
  resources :events do
    resources :comments, only: %i[create destroy index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save :down_case
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :password, presence: true, length: {minimum: 6}
  validates :name, presence: true, length: {minimum:3}
  validates :email, presence: true, length: {maximum:50},
            format: { with: VALID_EMAIL_REGEX },          
            uniqueness: { case_sensitive: false }

  has_many :events, foreign_key: :creator_id, dependent: :destroy
  has_many :invitations, foreign_key: :attendee_id, dependent: :destroy
  has_many :invited_events, through: :invitations, source: :event
  has_many :attended_events, through: :invitations, source: :event
  has_many :comments, foreign_key: :creator_id

  def upcoming_events
    attended_events.where('date >= ? AND accepted = ?', DateTime.now, true)
  end

  def previous_events
    attended_events.where('date < ? AND accepted = ?', DateTime.now, true)
  end
  
  private
  def down_case
    email.downcase!
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    redirect_to root_path unless !logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:sign_up_success] = "Thanks for signing in!!"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @my_events = @user.events.paginate(page: params[:page], per_page: 4).order('date DESC')
    @events = []
    @events = User.find(params[:id]).previous_events if params[:passed].present?
    @events = User.find(params[:id]).upcoming_events if params[:coming].present?
    respond_to do |format|
      format.json do
        if request.xhr?
          render :json => {:success => true, :html => (render_to_string("_events", :formats => [:html], :layout => false, :locals => {:events => @events})), data: @events}
        end
      end
 
      format.html {   }
    end
  end

  def invited_events
    @invited_events = Event.includes(:creator).where(id: Invitation.all.where(attendee_id: current_user.id,
                                                           accepted: false).pluck(:event_id))
    @accepted_button = true
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_events.html.erb
<% @events.each do |e| %>
  <div class="coming_and_passed_events">
    <div class="header-container">
      <h2>
        <%= e.title %>
      </h2>
    </div>
    <div class="body">
      <p>
        <%= e.location %>
      </p>
      <span class="badge badge-success"><%= e.creator.name %> is hosting this event!!</span>
      <p class="description"><%= e.description %></p>
    </div>
    <div class="footer">
      <span class="badge badge-info"><%= e.date.strftime('%Y %B %d %I:%M%p') %></span>
      <span class="badge badge-primary"><%= link_to "Details", event_path(e), remote: true %></span>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="form__title">
  <h3>Create your account</h3>
  <span>Bring the best events with your family and friends.</span>
</div>

<%= simple_form_for @user, url: '/sign_up', html: { multipart: true, class: "form__body" }  do |f| %>
  <div class="form__input">
    <%= f.input :name, placeholder: "First Name", label: false %>
  </div>

  <div class="form__input">
    <%= f.input :email, placeholder: "Emails Address", label: false %>
  </div>

  <div class="form__input">
    <%= f.input :password, placeholder: "Password", label: false %>
    <%= f.input :password_confirmation, placeholder: "Confirm Password", label: false %>
  </div>

  <span class="form__terms">By clicking sign up, you agree our <%= link_to 'Terms of use', "" %> and <%= link_to 'Privacy Policy', "" %></span>

  <div class="form__input">
    <%= f.submit 'Sign In', class: "form__sign-in-input" %>
  </div>
<% end %>

app/views/users/_sign_up_form.html.erb
<div class="form__title">
  <h3>Create your account</h3>
  <span>Bring the best events with your family and friends.</span>
</div>

<%= render "shared/messages" %>

<%= simple_form_for @user, url: '/sign_up', html: { multipart: true, class: "form__body" }  do |f| %>
  <div class="form__input">
    <%= f.input :name, placeholder: "First Name", label: false %>
  </div>

  <div class="form__input">
    <%= f.input :email, placeholder: "Email Address", label: false %>
  </div>

  <div class="form__input">
    <%= f.input :password, placeholder: "Password", label: false %>
    <%= f.input :password_confirmation, placeholder: "Confirm Password", label: false %>
  </div>

  <span class="form__terms">By clicking sign up, you agree our <%= link_to 'Terms of use', "" %> and <%= link_to 'Privacy Policy', "" %></span>

  <div class="form__input">
    <%= f.submit 'Sign Up', class: "form__sign-in-input" %>
  </div>
<% end %>

app/views/users/invited_events.html.erb
<%= javascript_pack_tag 'events' %>
<div class="container invitations">
  <br/>
  <%= render 'shared/header' %>
  <%= render 'shared/messages' %>
  <% if @invited_events.any? %>
    <div class="invitations__event">
      <%= render @invited_events %>
    </div>
  <% else %>
    <div class="alert alert-info alert-dismissible show" role="alert">
      <button type="button" id="close" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <p>You don't have invitations!!</p>
    </div>
    <div class="start-event-container">
      <h2>Start new Events and invite your friends!!</h2>
      <%= link_to 'Create a New Event', new_event_path, class: "create-event" %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= javascript_pack_tag 'script' %>
<%= render 'shared/header' %>

<div class="form">
  
  <div class="form__header">
    <%= link_to 'Sign Up', sign_up_path, class: "form__header--signup", id: "sign-up", remote: true %>
    <%= link_to 'Sign In', login_path, class: "form__header--signin", id: "sign-in", remote: true %>
  </div>

  <div class="form__container">
    <%= render 'sign_up_form' %>
  </div>

</div>

app/views/users/new.js.erb
  $("#sign-up").parent().next().html("<%= j render partial: 'sign_up_form' %>");
history.pushState('page212', 'Sessions.kz', '/sign_up')

app/views/users/show.html.erb
<%= javascript_pack_tag 'events' %>
<div class="profile-container">
  <%= render "shared/messages" %>
  <div class="row">
    <div class="col-md-12 col-lg-12 mt-5">
      <div class="events-container">
        <% if logged_in? && @user.id == current_user.id %>
          <%= link_to "Create a new event", new_event_path, class: "create-event" %>
        <% end %>
        <% if @user.events.any? %>
          <div class="user-event-details">
            <span class="badge badge-success"><span class="events_counter"><%= @user.events.count%></span> EVENTS IN YOUR DASHBOARD!!</span>
          </div>
          <div class="user_events_pagination">
            <%= will_paginate @my_events %>
          </div>
          <%= render @my_events.includes(:creator), show_edit: true %>
        <% else %>
          <div class="create-event-container">
            <strong>You have no events!!!</strong>
          </div>
        <% end %>
      </div>
    </div>
    <aside class="col-md-12 col-lg-12">
      <section class="user_info">
        <h1>
          <%= @user.name %>
        </h1>
        <div>
          <h5>You have these events in your schedule!!</h5>
          <div class="event-buttons" id='<% @user.id %>'>
            <%= link_to 'Upcoming events', profile_path(@user, params: { coming: 'true' }), class: "comming_request", :remote => true %>
            <%= link_to 'Passed events', profile_path(@user, params: { passed: 'true' }), class: "passed_request", :remote => true %>
          </div>
          <div class="content_custom_event">
        
          </div>
        </div>
      </section>
    </aside>
  </div>
</div>

<div class="popup popup-hide" id="popup">
  
</div>