config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  
  
  get 'profile/:id', to: 'users#show', as: 'profile'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'events/:id/invite', to: 'events#invite', as: 'invite_event'
  get 'events/:id/attend', to: 'events#attend', as: 'attend_event'
  get 'users/invitations', to: 'users#invited_events', as: 'invited_events'
  
  resources :events do
    resources :comments, only: %i[create destroy index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="error">
    <% obj.errors.full_messages.each do |msg| %>
      <span><%= msg %></span>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="header_sign_up">
  <div class="header_sign_up__logo">
    <span><%= link_to "JoinMe", root_path %></span>
  </div>
</header>

app/views/shared/_messages.html.erb
<%= javascript_pack_tag 'script' %>
<% if flash.any? %>
  <% flash.each do |name, msg| %>
    <div class='message <%="#{name}"%>' >
      <span><%= msg %></span>
    </div>
  <% end %>
<% end %>

app/views/shared/_navigation.html.erb
<div class="navigation">
  <input type="checkbox" class="navigation__checkbox" id="navi-toggle">
  <label for="navi-toggle" class="navigation__button">
    <span class="navigation__icon">&nbsp;</span>
    <% if current_user.invitations.where(accepted: false).count > 0 %>
      <small class="navigation__counter">
        <%= current_user.invitations.where(accepted: false).count %>
      </small>
    <% end %>
  </label>

  <div class="navigation__background">&nbsp;</div>

  <nav class="navigation__nav">
    <ul class="navigation__list">
      <% if logged_in? %>
        <li class="navigation__item">
          <span><%= current_user.name %></span>
        </li>
        <li class="navigation__item"><%=link_to 'Profile', profile_path(current_user.id), class: 'navigation__link'%></li>
      <% end %>
      <li class="navigation__item"><%=link_to 'Dashboard', root_path, class: 'navigation__link'%></li>
      <li class="navigation__item">
        <%=link_to invited_events_path, class: 'navigation__link' do %> 
          Invites
        <% end %></li>
      <li class="navigation__item"><%=link_to 'Log Out', logout_path, class: 'navigation__link'%></li>
    </ul>
  </nav>
</div>