config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  
  
  get 'profile/:id', to: 'users#show', as: 'profile'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'events/:id/invite', to: 'events#invite', as: 'invite_event'
  get 'events/:id/attend', to: 'events#attend', as: 'attend_event'
  get 'users/invitations', to: 'users#invited_events', as: 'invited_events'
  
  resources :events do
    resources :comments, only: %i[create destroy index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :invitations, foreign_key: :event_id
  has_many :attendees, through: :invitations, source: :attendee
  has_many :comments, dependent: :destroy
  is_impressionable

  validates :location, presence: true
  validates :image, presence: true, on: :create
  validates :date, presence: true
  validates :title, presence: true, length: {minimum:5}
  validates :description, presence: true, length: {minimum:10, maximum:800}

  scope :upcoming, -> { where('date >= ?', DateTime.now)}
  scope :passed, -> { where('date < ?', DateTime.now)}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :find_event, only: %i[show edit] 
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :user_id]

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    event_days_to_start @event
    if @event.save
      # byebug
      @value = Cloudinary::Uploader.upload(params[:event][:image])
      update_icon_url @value
      flash[:success] = "Congrats!! #{current_user.name}, your event will start in #{@days} days!!!.."
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params_update)
      flash[:success] = "Awesome #{@event.creator.name} your event has been saved!!"
      redirect_to profile_path(current_user)
    else
      flash.now[:danger] = 'Please check the form for errors.'
      render :edit
    end
  end

  def invite
    @event = Event.find_by(id: params[:id])
    @invitation = Invitation.find_or_create_by(attendee_id: params[:user_id], event_id: params[:id])
    attendee = User.find_by(id: params[:user_id])
    flash[:success] = "Great!! #{attendee.name} has recieved your invitation to this event."

    respond_to do |format|
      format.json do
        if request.xhr?
          render :json => {:success => true, :data => flash }
        end
      end
 
      format.html {   }
    end
  end

  def attend
    @invitation = Invitation.find_by(attendee_id: current_user.id, event_id: params[:id])

    if @invitation.update(accepted: true)
      flash[:success] = "Congrats #{current_user.name}, you are attending to this event!!.. #{@invitation.event.title} hosted by #{@invitation.event.creator.name}"
      redirect_to invited_events_path
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.js # show.js.erb
      format.json 
    end
  end

  private

  def event_params
    params.require(:event).permit(:location, :date, :description, :title, :image)
  end

  def event_params_update
    params.require(:event).permit(:location, :date, :description, :title)
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def load_current_user
    User.includes(:attended_events, :invitations, :events) if logged_in?
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_days_to_start event
    @days = (TimeDifference.between(event.date, DateTime.now).in_days).round()
  end

  def update_icon_url(value)
    @event = Event.last
    @event.image = value['url']
    @event.save
  end
end

app/views/events/_event.html.erb
<div class="events" id="<%= event.id %>">
  <div class="date-host">
    <div class="date-host__details">
      <strong><%= event.date.strftime('%Y %b %d %I:%M%p') %></strong>
      <% if @from_events_controller %>
        <small><%= event.creator.name %></small>
      <% end %>
      <div class="date-start">
          <% if event.date > DateTime.now %>
            <small>
              This event will start in:
            </small>
            <h4>
              <span class="badge badge-info"> <%= TimeDifference.between(event.date, DateTime.now).in_days.round %> days</span>
            </h4>
          <% else %>
            <small>
              <span class="badge badge-danger">Passed Event!</span>
            </small>
          <% end %>
      </div>
    </div>
    <% if event.image? %>
      <img src="<%= event.image %>" alt="Event image">
    <%end%>
  </div>
  
  <div class="details-event">
    <% if local_assigns[:show_edit] %>
      <div class="edit_event">
        <%= link_to edit_event_path(event) do %>
          <%= image_tag('edit.png') %>
        <% end %>
      </div>
    <% end%>
    <div class="title">
      <p><%= event.title %></p>
    </div>
    <div class="details">
      <div class="event-details">
        <p>
          <!-- <i class="fas fa-map-marker-alt"></i> -->
          <%= image_tag('geolocalize.png') %>
          <%= event.location %>
        </p>
        <p class="description"><%= event.description.truncate(350, separator: ' ') %></p>
        <% if event.date < Date.today %>
        <span class="badge badge-danger"><%= pluralize(event.invitations.where(accepted: true).count, "person") %> attended to this event!</span>
        <% else %>
          <span class="badge badge-danger"><%= pluralize(event.invitations.where(accepted: true).count, "person") %> are attending to this event!</span>
        <% end %>
        <% if logged_in? && current_user.id != event.creator_id %>
          <% if current_user.attended_events.any?%>
            <% if current_user.attended_events.ids.include? event.id && !@accepted_button%>
              <span class="badge badge-success">Attending</span>
            <% end %>
          <% end %>
        <% end %>
        <% if logged_in? && current_user.id == event.creator_id %>
          <% if event.date < Date.today %>
            <span class="badge badge-success"><%= event.creator.name %>, you hosted this event!!</span>
          <% else %>
            <span class="badge badge-success"><%= event.creator.name %>, you are hosting this event!!</span>
          <% end %>
        <% else %>
          <span class="badge badge-primary"><%= event.creator.name %> is the host</span>
        <% end %>
      </div>
      <div class="button-details">
        <% unless @accepted_button %>
          <%= link_to "See Details", event_path(event), remote: true %>
        <% end %>
        <% if @accepted_button %>
          <%= link_to "Accept event invitation", attend_event_path(event), class: 'event_button', method: :get %>
        <% end%>
      </div>
      <div class="footer-event">
        <div class="footer-event__right">
          <%= link_to pluralize(event.comments.count, 'Comment'), event_comments_path(event), remote: true %>
          <div class="views">
            <%= event.impressionist_count %>
            <span class="icon">Views</span>
          </div>
        </div>
        <div class="comments-popup popup-comments-hide"></div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for @event, html: { multipart: true, class: "form__body" }  do |f| %>
<div class="form__input">
  <%= f.input :title, placeholder: "Enter title", label: false %>
</div>

<div class="form__input">
  <%= f.input :location, placeholder: "Enter Location", label: false %>
</div>

<div class="form__input">
  <%= f.input :description, as: :text, placeholder: "Enter Description", label: false %>
</div>

<div class="form__input">
  <%= f.input :date, as: :datetime, placeholder: "Enter Date", label: false %>
</div>

<% if local_assigns[:hide_image].nil? %>
  <div class="form__input">
    <%= f.file_field :image %>
  </div>
<% end %>

<div class="form__input">
  <%= f.submit button, class: "form__sign-in-input" %>
</div>
<% end %>

app/views/events/_header.html.erb
<header class="header_sign_up">
  <div class="header_sign_up__logo">
    <span><%= link_to "JoinMe", root_path %></span>
  </div>
</header>

app/views/events/_show_event.html.erb
<%= javascript_pack_tag 'events' %>
<div class="popup__content row">
  <div class="popup__right col-md-12">

    <p class="popup__close">
      <%= image_tag "close.png" %>
    </p>
    <div class="show_event">
      <div class="show_event--header">
        <h2>
          <%= @event.creator.name %>'s event.
        </h2>
      </div>
      <div class="body">
        <p>
          <!-- <i class="fas fa-map-marker-alt"></i> -->
          <%= image_tag('geolocalize.png') %>
          <%= @event.location %>
        </p>
        <p class="description"><%= @event.description %></small></p>
      </div>
      <div class="footer">
        <span class="badge badge-success"><%= @event.date.strftime('%Y %B %d %I:%M%p') %></span>
      </div>
    </div>
    <% if logged_in? && current_user.id == @event.creator_id %>
      <% if @event.date > Date.today %>
        <span class="badge badge-primary badge-primary-invitations">You have <%= @event.invitations.where(accepted: false).count %> invitations pending... </span>
      <% end %>
    <% end %>
    <% if logged_in? && current_user.id == @event.creator_id %>
        <% if User.where.not(id: [current_user.id] + Invitation.all.where(event_id: @event.id).pluck(:attendee_id)).count != 0%>
          <% if @event.date < Date.today %>
            <div class="invite-people">
              <h4>This event is passed!!</h4>
            </div>
          <% else %>
            <div class="invite-people">
              <h4>Invite more people to your event</h4>
              <% User.where.not(id: [current_user.id] + Invitation.all.where(event_id: @event.id).pluck(:attendee_id)).each do |user| %>
                <%= link_to user.name, invite_event_path(id: @event.id, params: { user_id: user.id }), method: :get, class: "invite-people-item", remote: true %>
              <% end %>
            </div>
          <% end %>
        <% end %>
    <% end %>
    <% if @event.invitations.where(accepted: true).any? %>
      <div class="people-attending-container">
          <h2>People attending to this event:</h2>
          <% @event.invitations.where(accepted: true).each do |attendee| %>
            <span class="badge badge-info"><%= attendee.attendee.name %> </span>
          <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<%= render 'header' %>

<div class="form">
  <div class="go-back-to-profile">
    <%= link_to 'Back to profile', profile_path(current_user.id) %>
  </div>
  <div class="form__title">
    <h3>Edit your event</h3>
    <span>Enjoy your life by sharing awesome events!!!.</span>
  </div>

  <%= render 'form', hide_image: true, button: 'Save' %>

</div>

app/views/events/new.html.erb
<%= render 'header' %>

<div class="form">
  <div class="go-back-to-profile">
    <%= link_to 'Back to profile', profile_path(current_user.id) %>
  </div>
  <div class="form__title">
    <h3>Create your event</h3>
    <span>Enjoy your life by sharing awesome events!!!.</span>
  </div>

  <%= render 'form', button: 'Create' %>

</div>

app/views/events/show.js.erb
$("#popup").removeClass("popup-hide");
if ($("#popup").length) {
  setTimeout(() => {
    document.querySelector('.popup__content').classList.add('popup-display')
    console.log(document.querySelector('.popup__content'))
  }, 1)
}
$("#popup").html("<%= j render partial: 'show_event' %>");